
language: bash

env:
 - CLOUDQA_API_KEY="OnJaUYIkD+BFdVAY+nZBA44rE8y+ouq2q9OhMXQCjjM=" CLOUDQA_SUITE_ID=18 CLOUDQA_BROWSER=Chrome CLOUDQA_SEQUENTIAL_EXECUTION=false
 
before_script:
 - curl -O https://devcquserfiles.s3.amazonaws.com/98/764f2e3d2b7c4654bb3a73c15dcf4859/cloudqa-travisci.sh

script:
 - bash cloudqa-travisci.sh
