
# env:
#      - CLOUDQA_API_KEY="rKAN2ZIyUQDZLgL27E2oRmP5/uw4mZv4o7raYhQC+xE=" CLOUDQA_SUITE_ID=69 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG="CLI more information Test" CLOUDQA_BASE_URL="https://sandbox.cloudqa.io" RUN_SEQUENTIALLY=1#- task: CmdLine@2
#  inputs:
#    script: |
#      sudo apt-get update
#      
#      sudo apt-get install -y jq

# - task: Bash@3
#  inputs:
#    filePath: 'https://doc.cloudqa.io/files/cloudqa-bash.sh'
# production with environment https://cquserfiles.s3.amazonaws.com/5066/665857ca352e401491d344cda98c0849/cloudqa-stage-travisci.sh




script: 
    - bash cloudqa-stage-travisci.sh
