language: bash
addons:
    apt:
      update: true
before_script:
    - curl -O https://doc.cloudqa.io/files/cloudqa-jenkins.sh

script:
    - bash cloudqa-jenkins.sh "H/tJStnHZVLrYwT3aBBViMTVwuZBkDOoEQoVphLQ8pQ=" "1141" "Firefox" "user=Admin,pwd=admin" "1.0.1"
