language: bash

language: bash

env:
  - CLOUDQA_API_KEY="1La4je3UlXvFTjNeBqdAHKCG+2BDLd3o3BklEwfLv7k=" CLOUDQA_SUITE_ID=14 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="tp=java,input=admin" CLOUDQA_BUILD_TAG=variabletest CLOUDQA_BASE_URL="https://jqueryui.com/"

before_script:
  - curl -O https://devcquserfiles.s3.amazonaws.com/6/10d53c38ca5b4d719662e20920131830/cloudqa-travisci.sh
     
script:
  - bash cloudqa-travisci.sh

