
language: bash

env:
  - CIGNITI_API_KEY="W7cgN1dwnSuXkExtaYq7ZRHGgDKtZSJ31vQKSI8cg9g=" CIGNITI_SUITE_ID=3 CLOUDQA_BROWSER=Chrome CIGNITI_VARIABLES="input1=javas,rinput2=admin" CIGNITI_BUILD_TAG=TRAVISCI_CIGNITI CIGNITI_BASE_URL="https://www.seleniumeasy.com/" 1

before_script:
  - curl -O https://blueswan.s3.amazonaws.com/1/9ef5d11a53b64acfb03435351d12c357/cloudqa-travisci.sh

script:
  - bash cloudqa-travisci.sh
