env:
     - CLOUDQA_API_KEY="qWQgvZqigeMry9q9b4AKIU8jarQTK6JCgtI4aIMDCiA=" CLOUDQA_SUITE_ID=25 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG=Billing_Test CLOUDQA_BASE_URL="https://www.phptravels.net/" RUN_SEQUENTIALLY = 0

language: bash

before_script:
    - curl -O https://devcquserfiles.s3.amazonaws.com/6/6045b4de3d184574b1a7c2193f9d5368/cloudqa-travisci.sh

script: 
    - bash cloudqa-travisci.sh
