env:
     - CLOUDQA_API_KEY="vViZy6pvTAcIJav11vRuQlVteISq6hnpfgVWr9pfM28=" CLOUDQA_SUITE_ID=1997 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG=Billing_Test CLOUDQA_BASE_URL="https://erpnext.com/demo" RUN_SEQUENTIALLY = 0

language: bash

before_script:
    - curl -O https://devcquserfiles.s3.amazonaws.com/98/d9d0c396214d45358c27e51e7b34e70e/cloudqa-travisci.sh

script: 
    - bash cloudqa-travisci.sh
	
