     apt:
       update: true
 env:
   - CLOUDQA_API_KEY="W618C9WygaDYKc1bZ909F6k67m7cWxlbXIpweCQ93vg=" CLOUDQA_SUITE_ID=1141 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="name=Admin,pwd=admin" CLOUDQA_BUILD_TAG=invalidbaseurl CLOUDQA_BASE_URL="www.google.com"

 before_script:
     - curl -0 https://doc.cloudqa.io/files/cloudqa-jenkins.sh
     
 script:
    - bash cloudqa-jenkins.sh
