language: bash
addons:
    apt:
      update: true
before_script:
    - curl -O https://doc.cloudqa.io/files/cloudqa-jenkins.sh


script:
    - bash cloudqa-jenkins.sh "Jyl/vFArdVNlqwOwwUQUpAkNdL0IsLgUTxQmxc5+Jg8=" "1070" 
