language: bash

before_script:
    - curl -O https://doc.cloudqa.io/files/cloudqa-jenkins.sh

script:
    - bash cloudqa-jenkins.sh "5yTUF0WjtAQfYkszr2+36r27kVR2mgGgxYHZjxFyGhE=" "1137" "Chrome" "var1=abc,var2=efg" "2"
