env:
     - CLOUDQA_API_KEY="DJiKvMPbfAGVbLh/2BoBMkDjD2TxKSZTczpVPQ7T8R0=" CLOUDQA_SUITE_ID=3 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG=Billing_Test CLOUDQA_BASE_URL="https://www.seleniumeasy.com/" RUN_SEQUENTIALLY = 0

language: bash

before_script:
    - curl -O https://devcquserfiles.s3.amazonaws.com/98/d7dbb88acf494bb19237b20e4647d8cf/cloudqa-travisci%20(1).sh

script: 
    - bash cloudqa-travisci(1).sh
