
language: bash

env:
 - CLOUDQA_API_KEY="DJiKvMPbfAGVbLh/2BoBMkDjD2TxKSZTczpVPQ7T8R0=" CLOUDQA_SUITE_ID=19 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="name1=javas,input=admin" CLOUDQA_BUILD_TAG=Chrome_Retest1 CLOUDQA_BASE_URL="http://the-internet.herokuapp.com/"

before_script:
 - curl -O https://devcquserfiles.s3.amazonaws.com/98/07877366463b4a3286bd03e4214c37c9/cloudqa-travisci.sh

script:
 - bash cloudqa-travisci.sh
