# env:
#      - CLOUDQA_API_KEY="MPzTXks8vUKo0/at0yExuMZ0DqH+Nd+1/xybvc4pdiI=" CLOUDQA_SUITE_ID=2226 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG="CLI more information Test" CLOUDQA_BASE_URL="http://the-internet.herokuapp.com" RUN_SEQUENTIALLY=1
#- task: CmdLine@2
#  inputs:
#    script: |
#      sudo apt-get update
#      
#      sudo apt-get install -y jq

# - task: Bash@3
#  inputs:
#    filePath: 'https://doc.cloudqa.io/files/cloudqa-bash.sh'

env:
     - CLOUDQA_API_KEY="jI3xPHG/opQKVNnQO8rg52r1lsw+rNqM6eYDszK0nQU=" CLOUDQA_SUITE_ID=1146 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG="Variable test" CLOUDQA_BASE_URL="http://www.seleniumeasy.com" CLOUDQA_SEQUENTIAL_EXECUTION=TRUE CLOUDQA_ENVIRONMENT_NAME="qa" 

language: bash

before_script:
    - sudo apt-get update && sudo apt-get install -y jq
    - curl -O https://devcquserfiles.s3.amazonaws.com/5297/a853dcc0721c44229f60b1136ea3cb5b/cloudqa-stage-travisci.sh


script: 
    - bash cloudqa-stage-travisci.sh
    

