 env:
     - CLOUDQA_API_KEY="sK0dGPsG7XdXDEqDgkr+JrBHRWZQLsaX0YMBL8Es1Pw=" CLOUDQA_SUITE_ID=1419 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="name1=javas,pwd=admin" CLOUDQA_BUILD_TAG=chromewithvariableinput CLOUDQA_BASE_URL="https://app.cloudqa.io/"

 before_script:
     - curl -O https://doc.cloudqa.io/files/cloudqa-travisci.sh
     
 script:
     - bash cloudqa-travisci.sh
