env:
     - CLOUDQA_API_KEY="YDr2GUDqQvQFjcYmB48dHRchcYZ8jwJnO6UwhcnY+U4=" CLOUDQA_SUITE_ID=2051 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG="termination_test" CLOUDQA_BASE_URL="https://erpnext.com" RUN_SEQUENTIALLY=0

language: bash

before_script:
    - curl -O https://cquserfiles.s3.amazonaws.com/5066/af6b192b238d470ebb44edd1ffc5b942/cloudqa-travisciapp.sh

script: 
    - bash cloudqa-travisciapp.sh
    

