language: bash

env:
  - CLOUDQA_API_KEY="DJiKvMPbfAGVbLh/2BoBMkDjD2TxKSZTczpVPQ7T8R0=" CLOUDQA_SUITE_ID=17 CLOUDQA_BROWSER=IE CLOUDQA_VARIABLES="name1=javas,input=admin" CLOUDQA_BUILD_TAG=IE_Retest1 CLOUDQA_BASE_URL="http://the-internet.herokuapp.com/"

before_script:
  - curl -O https://devcquserfiles.s3.amazonaws.com/22/8e479e1abb6c43d78e230f8d6a112686/cloudqa-travisci.sh
     
script:
  - bash cloudqa-travisci.sh
  
