 env:
     - CLOUDQA_API_KEY="y4wiT1JOWM9wQq1cCgbRm0hKXF9ZNPnrBVXihWlBlCQ=" CLOUDQA_SUITE_ID=17 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="name1=javas,pwd=admin" CLOUDQA_BUILD_TAG=BasicTest CLOUDQA_BASE_URL="http://the-internet.herokuapp.com/"

before_script:
     - curl -O https://devcquserfiles.s3.amazonaws.com/22/8e479e1abb6c43d78e230f8d6a112686/cloudqa-travisci.sh
     
 script:
     - bash cloudqa-travisci.sh
     
     
     
