env:
     - CLOUDQA_API_KEY="YDr2GUDqQvQFjcYmB48dHRchcYZ8jwJnO6UwhcnY+U4=" CLOUDQA_SUITE_ID=2051 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG="termination_test" CLOUDQA_BASE_URL="https://erpnext.com" RUN_SEQUENTIALLY=0

language: bash

before_script:
    - sudo apt-get update && sudo apt-get install -y jq
    - curl -O https://doc.cloudqa.io/files/cloudqa-bash.sh

script: 
    - bash cloudqa-bash.sh
    

