language: bash

before_script:
    - curl -O https://doc.cloudqa.io/files/cloudqa-jenkins.sh

script:
    - bash cloudqa-jenkins.sh "5bMGXGRrwmUuaAE1H+lK+/pvoa5ztxiHG1phrYJApuM=" "1016" "Chrome" "var1=val1,var2=val2" "2"
