env:
     - CLOUDQA_API_KEY="SWdYKAHgJJxD8qdaiy9uy5whcI1JY34Q4uM1bOJyJBg=" CLOUDQA_SUITE_ID=1768 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="var1=val1,var2=val2" CLOUDQA_BUILD_TAG=Billing_Test CLOUDQA_BASE_URL="https://www.freecharge.in/" RUN_SEQUENTIALLY = 0

language: bash

before_script:
    - curl -O https://doc.cloudqa.io/files/cloudqa-travisci.sh

script: 
    - bash cloudqa-travisci.sh
