 env:
     - CLOUDQA_API_KEY="sK0dGPsG7XdXDEqDgkr+JrBHRWZQLsaX0YMBL8Es1Pw=" CLOUDQA_SUITE_ID=1309 CLOUDQA_BROWSER=Chrome CLOUDQA_VARIABLES="name=Admin,pwd=admin" CLOUDQA_BUILD_TAG=positivetest CLOUDQA_BASE_URL="http://www.seleniumeasy.com"

 before_script:
     - curl -O https://doc.cloudqa.io/files/cloudqa-travisci.sh
     
     
 script:
     - bash cloudqa-travisci.sh
